name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    name: Build (Docker + uv)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Sync dependencies with uv
        run: |
          uv venv
          uv sync --all-extras --dev

      - name: Verify uv environment
        run: |
          uv --version
          uv run python -c "import sys; print(sys.version)"
          uv run python -c "import LDDC; print('LDDC import ok')"

      - name: Build Docker image
        run: |
          docker build -t lddc-fastapi:latest .

      - name: Smoke run container and health check
        run: |
          docker run -d --name lddc-fastapi -p 8000:8000 lddc-fastapi:latest
          sleep 5
          curl --fail http://localhost:8000/health

      - name: Container logs on failure
        if: failure()
        run: |
          docker logs lddc-fastapi || true

      - name: Cleanup container
        if: always()
        run: |
          docker rm -f lddc-fastapi || true

  test:
    name: Test (uv pytest)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Sync dependencies with uv
        run: |
          uv venv
          uv sync --all-extras --dev

      - name: Run tests (exclude flaky network)
        run: |
          uv run pytest -q -k "not test_real_translation" --maxfail=1