name: Release Docker Image to GHCR

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

env:
  IMAGE_NAME: lddc-fastapi

jobs:
  build-and-test:
    name: Build & Test (gate release)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies (locked)
        run: uv sync --locked

      - name: Run tests (exclude flaky network)
        run: uv run pytest -q -k "not test_real_translation" --maxfail=1

      - name: Docker build smoke (ensure Dockerfile builds)
        run: docker build -t ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} .

  build-and-push:
    name: Build & Push Image
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} .

      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

      - name: Create Release with image info
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Docker Image available:
            `docker pull ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}